

name: 🚨 Main WorkFlow

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [ "master",  "development"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: blank-${{ github.ref }}
  cancel-in-progress: true


jobs:

  lint:
    name: Lint Checks
    runs-on: ubuntu-latest
    env:
      MOVIE_API_KEY: ${{ secrets.MOVIE_API_KEY }} # Available to all steps in this job

    steps:
      - uses: actions/checkout@v4

      - name: Give gradlew execute permission
        run: chmod +x ./gradlew


# ultimate cache for gradle save significant time while building

      - name: Setup Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Run lint
        run: ./gradlew lintDebug

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html


  unit-test:

    name: Unit Test
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Give gradlew execute permission
        run: chmod +x ./gradlew

#      - name: Setup Gradle cache
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-

      - name: Run tests
        run: ./gradlew test

      - name: Upload the test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/